### ISSUE TITLE
comment search API channel과 video 분리 문의

### ISSUE THREAD

**Issue by ssongjay** [youtube-comment-search/wiki#8]
API 규격 문의도 위키에 올려도 되나 고민이었지만 server 레포의 이슈보다는 여기가 더 공용으로 논의하기에 좋아보여 라벨 생성하고 문의 납깁니다.

먼저 댓글관련 response에서 channel과 video 차이는 일단 없다는 가정하에 진행중에 생긴 고민임을 알립니다. (차이가 있다면 분리가 우선적으로 맞지만 차이가 없어 고민중)
channel과 video의 댓글들을 보내주는 api를 만들고 있습니다. API의 파라미터에는 채널 댓글 검색 - channelId, 동영상 댓글 검색 - videoId 가 요구 됩니다. 그렇다면 요구하는 파라미터가 채널id인지 비디오id인지 알아야 합니다. 그 방법으로는 파라미터에 id와 type을 보내주기 보단 channelId, videoId로 들어오는게 편리하고 좋아보여 원래 논의한 api와 다르게 /search/comment 에서 각각 video와 channel로 api를 분리하는게 어떨까 싶습니다.

지금은 일단 /search/comment-channel, /search/comment-video로 기능 구현한 상태이고 /search/comment/channel, /search/comment/video로 리팩토링할 계획입니다.

**Comment by byhhh2** [comment]
isChannelId 활용

**Comment by byhhh2** [comment]
type으로 변경 (string)
